name: release-packages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: nikki_*
          merge-multiple: true

      - name: Cek isi artifact hasil download
        run: |
          echo "Isi root:"
          ls -lh
          echo "Isi semua subfolder:"
          find . -type f
          find . -type d

      - name: Compress each package jika ada .ipk
        run: |
          for d in nikki_*; do
            [ -d "$d" ] || continue
            if compgen -G "$d/*.ipk" > /dev/null; then
              tar -czf "$d.tar.gz" -C "$d" .
              echo "Berhasil kompres $d ke $d.tar.gz"
            else
              echo "Folder $d tidak ada file .ipk, skip compress."
            fi
          done

      - name: List files after compress
        run: ls -lh *.tar.gz || true

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            nikki_*.tar.gz
          generate_release_notes: true
