name: release-packages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  get-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.ref_name }}

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep 'PKG_VERSION:=' ./luci-app-nikki/Makefile | awk -F '=' '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "New Version: ${VERSION}"

  release:
    name: ${{ matrix.arch }}-${{ matrix.branch }} release
    needs: get-version
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_generic
        branch:
          - openwrt-23.05
          - openwrt-24.10
        exclude:
          - arch: aarch64_cortex-a76
            branch: openwrt-23.05

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: luci-app-nikki
          INDEX: 1
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          NO_REFRESH_CHECK: true

      - name: compress
        run: |
          tar -c -z -f nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz -C bin/packages/${{ matrix.arch }}/nikki .
          mkdir -p public/${{ matrix.branch }}/${{ matrix.arch }}
          mv bin/packages/${{ matrix.arch }}/nikki public/${{ matrix.branch }}/${{ matrix.arch }}
          tar -c -z -f feed_nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz public/${{ matrix.branch }}/${{ matrix.arch }}

      - if: github.event_name == 'push' && startsWith(github.ref_name, 'v')
        name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.get-version.outputs.version }}"
          files: |
            nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz
          generate_release_notes: true

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: feed_nikki_${{ matrix.arch }}-${{ matrix.branch }}
          path: feed_nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz

  feed:
    needs: release
    name: feed
    runs-on: ubuntu-latest

    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          pattern: feed_nikki_*
          merge-multiple: true
      
      - name: uncompress
        run: |
          for file in feed_nikki_*.tar.gz; do tar -x -z -f "$file"; done
      
      - name: prepare
        run: |
          echo "${{ secrets.KEY_BUILD_PUB }}" > public/key-build.pub
          echo "${{ secrets.PUBLIC_KEY }}" > public/public-key.pem
          tree --dirsfirst --sort name -P '*.apk|*.ipk' --prune --noreport -H "" -T "Nikki's Feed" --charset utf-8 -o public/index.html public
          sed -i '/<p class="VERSION">/,/<\/p>/d' public/index.html

      - name: feed
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy public --project-name=nikkinikki