name: release-packages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: nikki_*
          merge-multiple: true

      - name: List downloaded files
        run: ls -lhR

      - name: Compress each package
        run: |
          for d in nikki_*; do
            [ -d "$d" ] || continue
            tar -czf "$d.tar.gz" -C "$d" .
          done

      - name: List files for release
        run: ls -lh

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            nikki_*.tar.gz
          generate_release_notes: true
