name: Sync Fork With Upstream

on:
  schedule:
    - cron: '0 2 * * *' # Setiap hari jam 09:00 WIB
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote if not exists
        run: |
          git remote | grep upstream || git remote add upstream https://github.com/nikkinikki-org/OpenWrt-nikki.git

      - name: Fetch and merge upstream
        run: |
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main || (echo "::error ::Merge conflict detected! Please resolve manually." && exit 1)
      
      - name: Push to origin
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
